### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by AbdelrhmanKassem** [AbdelrhmanKassem/exams-webapp-backend#15]
Test coverage needs to be improved for
  * QR Code generation API
  * More scrutinizing of index actions with filters and sort
  * External GET Exam API
  * Cheat Cases Endpoints

**Comment by seifgneedy** [comment]
Any updates?

**Comment by AbdelrhmanKassem** [comment]
@seifgneedy Couldn't make the time to work on this, swarmed with other tasks, perhaps if you want to give it a crack we can connect offline and I can onboard you to get started

**Comment by seifgneedy** [comment]
Great, I'm busy thank you!
